# Generated by Django 4.0.6 on 2022-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('img', models.ImageField(default=None, upload_to='tag_images')),
                ('url', models.URLField(blank=True, default='')),
                ('description', models.TextField(default='no description yet')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(default=None, upload_to='post_images')),
                ('description', models.TextField(default='no description yet')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(to='main_blog.tag')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
