# Generated by Django 4.0.6 on 2023-02-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_format',
            field=models.CharField(default='html', max_length=10),
        ),
    ]
